### ISSUE TITLE
Empty folders api and frontend while creating new app

### ISSUE THREAD

**Issue by Callenowy** [terminalvelocity/seeds.js#95]
Hey,
I got issue with creating new app. After typing "seeds new myDemoApp" in console I got empty folders app and frontend. 
I tried:
npm uninstall seeds
npm cache clean
bower cache clean
npm install -g seeds

and issue still exists.

![image](https://cloud.githubusercontent.com/assets/10743192/13723486/85e59f72-e867-11e5-915a-19c8fceaaa83.png)

![image](https://cloud.githubusercontent.com/assets/10743192/13723518/54f737d0-e868-11e5-9979-4c40bf3f3914.png)

Working on Windows 10 Pro,
using CMDer as console and running as administrator.

Any ideas how to solve it?

**Comment by sharpharp** [comment]
Yeah, unfortunately at this point, issues with Windows systems are to be expected.

Just so you know where the problem lies, there are a couple of pretty crucial pieces of seeds that need to be rewritten to make everything smoother on that front, and the next major refactor should alleviate those issues.
 At the moment, Windows support is still a tough one for us to test, but, if you have Screenhero, we can put our heads together and help you troubleshoot. 

The feedback helps more than you know, so keep it coming. For now, the recommended way to use seeds on windows is with kitematic or vagrant (or some other virtual machine).

**Comment by jhliberty** [comment]
Finally got a windows tester 

Using Kitematic/Docker on windows with https://hub.docker.com/r/seeds/envbase/ we were able to get seeds fully working on Windows.

![seeds-on-windows2](https://cloud.githubusercontent.com/assets/449321/14057624/d9dad720-f2d3-11e5-9d35-270f7043e034.png)

![seeds-on-windows](https://cloud.githubusercontent.com/assets/449321/14057625/dfb8d0e8-f2d3-11e5-958f-2c674e84f906.png)

The dockerfile could use a minor amount of tweaking but it does work and is the recommended way to use Seeds on windows. If you have any issues getting up and running feel free to post a new issue or join us on the [gitter chat](https://gitter.im/terminalvelocity/seeds.js).
